# Generated by Django 6.0.7 on 2026-07-24 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(help_text='E.g., 0771234567', max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('delivery_zone', models.CharField(choices=[('inside_kampala', 'Inside Kampala (Delivery: 5,000 UGX)'), ('outside_kampala', 'Outside Kampala / Central Uganda (Delivery: 10,000 UGX)'), ('pickup', 'I will pick it up myself (Free Delivery)')], default='inside_kampala', max_length=20)),
                ('address', models.CharField(help_text="E.g., 'Nakasero, near the market'", max_length=255)),
                ('landmark', models.CharField(blank=True, help_text="E.g., 'Next to the red building'", max_length=100, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending (Waiting for Justin to confirm)'), ('confirmed', 'Confirmed (Justin is fetching the shoe)'), ('shipped', 'Shipped (Out for delivery via boda-boda)'), ('delivered', 'Delivered (Customer received the shoe)'), ('cancelled', 'Cancelled (Customer changed mind or shoe unavailable)')], default='pending', max_length=20)),
                ('payment_method', models.CharField(choices=[('momo', 'MTN Mobile Money (MoMo)'), ('airtel', 'Airtel Money'), ('cash', 'Cash on Delivery (Pay when shoe arrives)')], default='cash', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal notes for Justin', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer Order',
                'verbose_name_plural': 'Customer Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending (Waiting for Justin to confirm)'), ('confirmed', 'Confirmed (Justin is fetching the shoe)'), ('shipped', 'Shipped (Out for delivery via boda-boda)'), ('delivered', 'Delivered (Customer received the shoe)'), ('cancelled', 'Cancelled (Customer changed mind or shoe unavailable)')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='orders.order')),
            ],
            options={
                'verbose_name': 'Status Log',
                'ordering': ['timestamp'],
            },
        ),
    ]
