# Generated by Django 6.0.7 on 2026-07-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_zone',
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text="Enter fee based on customer's distance", max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending (Waiting for Justin to confirm)'), ('confirmed', 'Confirmed (Justin is fetching the shoe)'), ('shipped', 'Shipped (Out for delivery)'), ('delivered', 'Delivered (Customer received the shoe)'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total cost of the shoes only', max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Auto-calculated: Subtotal + Delivery Fee', max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderstatuslog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending (Waiting for Justin to confirm)'), ('confirmed', 'Confirmed (Justin is fetching the shoe)'), ('shipped', 'Shipped (Out for delivery)'), ('delivered', 'Delivered (Customer received the shoe)'), ('cancelled', 'Cancelled')], max_length=20),
        ),
    ]
