# Generated by Django 6.0.7 on 2026-07-24 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Primary contact number (E.g., 0771234567)', max_length=15)),
                ('default_address', models.CharField(blank=True, help_text="E.g., 'Nakasero, near the market'", max_length=255, null=True)),
                ('default_landmark', models.CharField(blank=True, help_text="E.g., 'Next to the red building'", max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='If a customer is troublesome, uncheck this to block them from ordering')),
                ('admin_notes', models.TextField(blank=True, help_text="Internal notes about this customer (E.g., 'Always pays late', 'VIP customer')", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Profile',
                'verbose_name_plural': 'Customer Profiles',
            },
        ),
    ]
