# Generated by Django 6.0.7 on 2026-07-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(help_text="E.g., 'Today I am near Kampala Road / Nakasero'", max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Check this to show the banner to customers on the website')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily Location Banner',
                'verbose_name_plural': 'Daily Location Banner',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='FootStyle', max_length=50)),
                ('slogan', models.CharField(default='Fashion Starts from the Ground Up.', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('currency', models.CharField(default='UGX', max_length=3)),
                ('default_delivery_fee', models.DecimalField(decimal_places=2, default=5000.0, max_digits=10)),
                ('whatsapp_number', models.CharField(default='2567XXXXXXXX', max_length=15)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
