# Generated by Django 6.0.7 on 2026-07-24 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(help_text="E.g., 'women', 'men', 'kids'", unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, help_text='Regular price in UGX', max_digits=10)),
                ('promotional_price', models.DecimalField(blank=True, decimal_places=2, help_text='Sale price in UGX (Leave blank if no sale)', max_digits=10, null=True)),
                ('sizes_available', models.CharField(help_text="E.g., '38, 39, 40, 41'", max_length=100)),
                ('colors_available', models.CharField(help_text="E.g., 'Red, Black, Blue'", max_length=100)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('availability_status', models.CharField(choices=[('in_stock', 'In Stock (Ready to deliver now)'), ('available_to_order', 'Available to Order (I will fetch it)'), ('out_of_stock', 'Out of Stock (Unavailable)')], default='in_stock', max_length=20)),
                ('is_featured', models.BooleanField(default=False, help_text='Show this on the Homepage?')),
                ('views', models.PositiveIntegerField(default=0, help_text='Tracks popularity for sorting')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.category')),
            ],
            options={
                'verbose_name': 'Product (Shoe)',
                'verbose_name_plural': 'Products (Shoes)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='1 to 5 Stars')),
                ('comment', models.TextField()),
                ('customer_name', models.CharField(max_length=100)),
                ('is_approved', models.BooleanField(default=False, help_text='Justin must approve reviews before they show on site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Product Review',
                'ordering': ['-created_at'],
            },
        ),
    ]
